### ISSUE TITLE
2x版本无法使用脚本创建账户

### ISSUE THREAD

**Issue by cxbl-ops** [FISCO-BCOS/FISCO-BCOS-DOC#1729]
我在使用2.x版本时遇到问题，使用脚本创建账户提示

![image](https://github.com/FISCO-BCOS/FISCO-BCOS-DOC/assets/119595868/58d00aa2-bf66-4bb6-b9d0-8e8cf42a8f5b)
但我的openssl已经安装
![image](https://github.com/FISCO-BCOS/FISCO-BCOS-DOC/assets/119595868/90ef3c76-1fd4-45da-a80b-46b9b909cee6)

**Comment by JimmyShi22** [comment]
请根据文档使用相应版本的openssl
