### ISSUE TITLE
console.tar.gz文件地址貌似变动

### ISSUE THREAD

**Issue by wudenggang0** [FISCO-BCOS/FISCO-BCOS-DOC#246]
文件无法完全下载
![image](https://user-images.githubusercontent.com/3587832/54280309-20f6ba80-45d2-11e9-9fd7-99785562a5ed.png)
另外地址貌似变动
![image](https://user-images.githubusercontent.com/3587832/54280036-77afc480-45d1-11e9-9bfc-829f8328830d.png)
console.tar.gz地址疑似变更为：https://github.com/FISCO-BCOS/LargeFiles/blob/master/tools/console.tar.gz

**Comment by fqliao** [comment]
下载地址是变动了，控制台下载和使用参考最新文档https://fisco-bcos-documentation.readthedocs.io/zh_CN/release-2.0/docs/manual/console.html。
