### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by jspasovski** [FISCO-BCOS/FISCO-BCOS-DOC#276]
Hi BCOS team,

Will there be an english version of the documentation for version 2.0 available in the near future?

Regards,
Jason

**Comment by HaoXuan40404** [comment]
Yes, we have this plan, the English version is working now

**Comment by HaoXuan40404** [comment]
yes, we are working now

**Comment by HaoXuan40404** [comment]
Hi~, English version of the documentation for version 2.0 is available now! [Click here](https://fisco-bcos-documentation.readthedocs.io/en/latest/docs/installation.html) to build your blockchain
