### ISSUE TITLE
run.sh出错

### ISSUE THREAD

**Issue by lilianwen** [FISCO-BCOS/FISCO-BCOS-DOC#277]
ubuntu 16.04
release-2.0分支
执行bash run.sh出错。出错信息如下：
Exception occurred:
  File "/usr/local/lib/python3.5/dist-packages/docutils/parsers/rst/roles.py", line 355, in math_role
    text = rawtext.split('`')[1]
IndexError: list index out of range

**Comment by HaoXuan40404** [comment]
这个可能是python3的问题，建议你使用python2.7试一下

**Comment by HaoXuan40404** [comment]
建议通过https://readthedocs.org/  在线配置，本地编译需要依赖较多的包，网页上会方便一些
