### ISSUE TITLE
机构A、C构建群组2中“cp -r ~/generator ~/generator-C”不严谨

### ISSUE THREAD

**Issue by jinjzk** [FISCO-BCOS/FISCO-BCOS-DOC#427]
文档中有一段话
“初始化机构C，请注意，此时generator目录下有链证书及私钥，实际环境中机构C无法获取链证书及私钥。”
使用cp拷贝目录会把链证书一并拷贝到其他节点，既然大大们已经发现这是一个不严谨的操作，那为什么还刻意为之，在区块链的世界，证书大于一切，相信大家都懂，所以建议除了在机构A、C构建群组2的这个步骤中继续使用上一个文档版本的命令
“git clone https://github.com/FISCO-BCOS/generator.git /bcos/generator-C”

**Comment by HaoXuan40404** [comment]
感谢反馈，实际应用场景中，generator的下载应该由用户直接完成。教程中直接拷贝了generator整个目录是为了简化操作，减少步骤。
